
INSERT INTO ROLE (ID_ROLE, NAME) VALUES (1, 'ROLE_USER');
INSERT INTO ROLE (ID_ROLE, NAME) VALUES (2, 'ROLE_ADMIN');
INSERT INTO ROLE (ID_ROLE, NAME) VALUES (3, 'ROLE_MOD');

INSERT INTO GENRE (ID_GENRE, NAME) VALUES(1,'Action');
INSERT INTO GENRE (ID_GENRE, NAME) VALUES(2,'Adventure');
INSERT INTO GENRE (ID_GENRE, NAME) VALUES(3,'Comedy');
INSERT INTO GENRE (ID_GENRE, NAME) VALUES(4,'Crime');
INSERT INTO GENRE (ID_GENRE, NAME) VALUES(5,'Drama');
INSERT INTO GENRE (ID_GENRE, NAME) VALUES(6,'Fantasy');
INSERT INTO GENRE (ID_GENRE, NAME) VALUES(7,'Historical');
INSERT INTO GENRE (ID_GENRE, NAME) VALUES(8,'Horror');
INSERT INTO GENRE (ID_GENRE, NAME) VALUES(9,'Mystery');
INSERT INTO GENRE (ID_GENRE, NAME) VALUES(10,'Paranoid');
INSERT INTO GENRE (ID_GENRE, NAME) VALUES(11,'Philosophical');
INSERT INTO GENRE (ID_GENRE, NAME) VALUES(12,'Political');
INSERT INTO GENRE (ID_GENRE, NAME) VALUES(13,'Romance');
INSERT INTO GENRE (ID_GENRE, NAME) VALUES(15,'Saga');
INSERT INTO GENRE (ID_GENRE, NAME) VALUES(16,'Satire');
INSERT INTO GENRE (ID_GENRE, NAME) VALUES(17,'Science fiction');
INSERT INTO GENRE (ID_GENRE, NAME) VALUES(18,'Thriller');
INSERT INTO GENRE (ID_GENRE, NAME) VALUES(19,'Urban');
INSERT INTO GENRE (ID_GENRE, NAME) VALUES(20,'Western');


